kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pipeline-binding
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: pipeline-demo
roleRef:
  kind: Role
  name: pipeline-role
  apiGroup: rbac.authorization.k8s.io
