apiVersion: types.kubefed.k8s.io/v1beta1
kind: FederatedService
metadata:
  name: reverse-words
  labels:
    name: reverse-words
spec:
  template:
    metadata:
      labels:
        name: reverse-words
    spec:
      type: ClusterIP
      ports:
        - port: 8080
          targetPort: 8080
          protocol: TCP
      selector:
        name: reverse-words
  placement:
    clusters:
    - name: cluster1
    - name: cluster2
    - name: cluster3
